class elems_IGMembershipReversalRequest {
    static BTN_SUBMIT = '//button[@form="formIGReversalRequest"]'
    static BTN_CANCEL = '//button[@id="submit"]/following-sibling::button'
    static DATE_REQUESTEDDATE = '//label[@id="dtpRequestedDate_label"]/following-sibling::div/span'
    static LBL_REVERSALREQUESTID = '//label[text()="Reversal Request ID"]/following-sibling::div'
    static LBL_SAFRAMEMBERID = '//label[@for="pckSAFRAMemberId"]'
    static LBL_CUSTOMERNAME = '//label[@for="lblCustomerName"]'
    static LBL_SAFRAMEMBERSHIPSTATUS = '//label[text()="SAFRA Membership Status"]/following-sibling::div'
    static LBL_SAFRAMEMBEREXPIRYDATE = '//label[text()="SAFRA Membership Expiry Date"]/following-sibling::div'
    static LBL_IGMEMBERSHIPID = '//label[text()="Interest Group Membership ID"]/following-sibling::div'
    static LBL_INTERESTGROUP = '//label[text()="Interest Group"]/following-sibling::div'
    static LBL_IGTERMSTART = '//label[text()="Interest Group Term Start"]/following-sibling::div'
    static LBL_IGTERMEND = '//label[text()="Interest Group Term End"]/following-sibling::div'
    static LBL_STATUS = '//label[text()="Status"]/following-sibling::div'
    static LBL_REASONCODE = '//label[text()="Reason Code"]/following-sibling::div'
    static LBL_REQUESTDATE = '//label[text()="Request Date"]/following-sibling::div'
    static LBL_PROCESSEDDATE = '//label[text()="Processed Date"]/following-sibling::div'

    static CHK_CALCULATEPAYMENT = '//input[@id="chkCalculatePayment"]'
    static CHK_REFUNDCREDIT = '//input[@id="chkGiveRefundCredit"]'
    static DRP_REFUNDCREDIT = '//span[@id="drpRefundCreditType"]'
    static DRP_AMOUNTTYPE = '//span[@id="drpAmountType"]'
    static TXTAREA_REFUNDCREDIT = '//textarea[@id="txtRefundCreditReason"]'
    static TBL_PAYMENTDETAIL = '(//h3[text()="Payment Detail"]/parent::div//table)[1]'

    static BTN_ADDWIAVER = '//button[text()="Add Waiver Off"]'
    static TBL_WIAVER = '(//button[text()="Add Waiver Off"]/parent::div/parent::div/following-sibling::div//table)[2]'
    static DRP_CHARGETYPE = '//span[@id="drpChargeType"]'
    static TXT_AMOUNT = '//input[@id="txtAmount"]'
    static TXT_REASON = '//textarea[@id="txtReason"]'
    static BTN_CONFIRM = '//button[text()="Confirm"]'
    static BTN_CANCEL = '//button[text()="Confirm"]/following-sibling::button'
    static LBL_TOTAL = '//label[@for="txtTotal"]'
    static LBL_TOTALREGCHRG = '//label[text()="Total Registration Charges Being Cancelled:"]/following-sibling::div'
    static LBL_TOTALRENCHRG = '//label[text()="Total Renewal Charges Being Cancelled:"]/following-sibling::div'
    static LBL_TOTALDEFRCHRG = '//label[text()="Total Deferment Charges Being Cancelled:"]/following-sibling::div'
    static LBL_TOTALPAIDIGMEM = '//label[text()="Total Paid For IG Membership:"]/following-sibling::div'
    static LBL_BALANCEDAMOUNT = '//label[text()="Balanced Amount:"]/following-sibling::div'
    static LBL_REFUNDAMOUNT = '//label[text()="Refund Amount:"]/following-sibling::div'
    static LBL_REFUNDBALANCE = '//label[text()="Refund Balance:"]/following-sibling::div'
    static LBL_ISPAYMENTCOLLECTED = '//label[text()="Is Payment Collected:"]/following-sibling::div'
}

export default elems_IGMembershipReversalRequest
