const E2EData = {

// FS - 016 INTEREST GROUP REGISTRATION AND RENEWAL

MEMBERID_FOR_IG_REGISTRATION : 'S2102786C',
MEMBERID_FOR_IG_RENEWAL : 'A300001781',
BATCH_MEMBER_REGISTRATION_WITH_EXISTING_MEMBER_USING_DEFUALT_IG : 'A300000511',
BATCH_MEMBER_REGISTRATION_WITH_EXISTING_MEMBER_USING_NON_DEFUALT_IG : 'A300001194',

IG_DEACTIAVATION : '',
MEMBER_NAME_FOR_IG_CONVERSION : 'Testuser007',
MEMBER_NAME_FOR_IG_DEFERMENT : 'MemBR 1',
MEMBERID_AND_NAME_FOR_IG_TERMINATION : {

    MEMBERID : 'A300001811',
    MEMBERNAME: 'Tong Hui'
},
MEMBERID_FOR_IG_REINSTATEMENT : {
   
    MEMBERID : 'A300001811',
    MEMBERNAME: 'Tong Hui'
},
MEMBER_NAME_FOR_IG_REVERSAL : 'Auto-User4345',
MEMBER_NAME_FOR_IG_WAIVER : 'Auto-User7632',




}   

export default E2EData 