class elems_MembershipRenewalAdviceSettingDetail{

    static BTN_SAVE = '//span[text()="Save"]'
    static BTN_CANCEL = '//span[text()="Cancel"]'
    static TXT_NAME = '//input[@id="txtName"]'
    static BTN_CREATENEW = '//span[text()="Create New"]'
    static TXTAREA_DESCRIPTION = '//textarea[@id="txtDescription"]'
    static DRP_MEMBERCATEGORY = '//span[@id="drpMemberCategory"]'
    static DRP_GENDER = '//span[@id="drpGender"]'
    static LST_MEMBERTYPECODE = '//input[@id="txtMemberTypeCode"]'
    static PCK_MEMBERTYPECODE = '(//button[@class="k-button k-button-md k-button-solid k-button-solid-base k-rounded-md"])[2]'
    static DRP_MEMBERSTATUSREASON = '//span[@id="drpMemberStatusReason"]'
    static PCK_EXPIRYDATEFROM = '//input[@id="dtpExpiryDateFrom"]'
    static PCK_EXPIRYDATETO = '//input[@id="dtpExpiryDateTo"]'
    static PCK_DATEOFBIRTHFROM = '//input[@id="dtpDateOfBirthFrom"]'
    static PCK_DATEOFBIRTHTO = '//input[@id="dtpDateOfBirthTo"]'
    static DRP_MEMBERCARDTYPE = '//span[@id="drpMemberCardType"]'
    static CHK_EXCLUDEBADADDRESSFLAG = '//input[@id="checkExcludeBadAddressFlag"]'
    static CHK_EXCLUDETERMINATEDINADVANCED = '//input[@id="checkExcludeTerminatedInAdvance"]'
    static CHK_EXCLUDEREGISTRATIONINADVANCE = '//input[@id="checkExcludeRegistrationInAdvance"]'
    static TXT_POSTALCODE = '//input[@id="txtPostalCode"]'
    static TXT_ZONEID = '//input[@id="txtZoneId"]'
    static DRP_MARITALSTATUS = '//span[@id="drpMaritalStatus"]'
    static DRP_AUTODEDUCT = '//span[@id="drpAutoDeduction"]'
    static TBL_MEMBERSHIPRENEWALADICE = '//h2[text()="Membership Renewal Advice Setting Listing"]/ancestor::div//table'
}
export default elems_MembershipRenewalAdviceSettingDetail