const E2EData = {

   // FS - 040 Card Management

   MEMBERID_VOLUNTERR_CARD_MANAGEMENT : 'A300000835',
   MEMBER_NAME_VOLUNTERR_CARD_MANAGEMENT : 'TestUser884B',
   LAST4DIGITNRIC_VOLUNTERR_CARD_MANAGEMENT : '884B',
   CARD_TYPE_VOLUNTERR_CARD_MANAGEMENT : 'SAFRA DBS Credit Card',


   MEMBERID_SAFRA_CARD_MANAGEMENT : 'A300000830',
   MEMBER_NAME_SAFRA_CARD_MANAGEMENT : 'TesterMeminfo',
   LAST4DIGITNRIC_SAFRA_CARD_MANAGEMENT : '253F',
   CARD_TYPE_SAFRA_CARD_MANAGEMENT : 'SAFRA DBS Credit Card',


   MEMBERID_VIP_CARD_MANAGEMENT : 'A300000836',
   MEMBER_NAME_VIP_CARD_MANAGEMENT : 'TestUser512H',
   LAST4DIGITNRIC_VIP_CARD_MANAGEMENT : '512H',
   CARD_TYPE_VIP_CARD_MANAGEMENT : 'SAFRA DBS Credit Card',

   }   
   
   export default E2EData 